### ISSUE TITLE
Incremental Updates

### ISSUE THREAD

**Issue by vrann** [magento-engcom/bulk-api#17]
Support for incremental updates should address the problem of the third-party systems which persists multiple entities without checking did they really change. Every entity which is persisted should have hash generated for the data. When persistence operation starts, it will load the entity from the database and calculate the hash on key data which is imported. In case if the hash is not changed, an entity should be skipped from the persistence.

Redis can be used in middleware to check is there differences between post requests; Incremental updates.
Besides, Resource Models can be optimized to be able to calculate the hash before persistence starts

**Comment by nuzil** [comment]
https://github.com/magento/async-import/issues/27
