### ISSUE TITLE
Inconsistent usages of Async vs Asynchronous 

### ISSUE THREAD

**Issue by careys7** [magento-engcom/bulk-api#18]
Currently we make use of both `async` and `asynchronous`, eg:

- `WebApiAsyncBaseTestCase`
- `AsynchronousSchemaRequestProcessor`
- `AsynchronousRequestProcessor`
- `Magento_WebapiAsync`
- `Magento\WebapiAsync\Api\Data\AsyncResponseInterface`

In the existing module for AsynchronousOperations it is already using the full spelling.

Is it worth choosing one option, and then renaming these prior to release?

**Comment by nuzil** [comment]
Good question. @vrann what is a good way on Magento standard to do it?

**Comment by joshuaadickerson** [comment]
I like standardizing it. The abbreviation is much easier for everyone. I don't think anyone reading any code would be confused that "async" means "asynchronous". I am pretty sure I've never written something that uses the long form and can't recall any instance of reading any code where the long form is used. It almost seems unnatural.

That being said, asynchronous or asynchronously (any version of the long form) makes sense to use in documentation, at least once.
