### ISSUE TITLE
Performance optimizations on Save for Bulk products endpoint

### ISSUE THREAD

**Issue by misha-kotov** [magento-engcom/bulk-api#2]
As a Magento developer, I would like the Catalog Bulk API endpoints on Save to be optimized so that bulk Save operations execute as quickly as possible. 

Currently many different actions are performed by Magento as a result of a product save. One example of such action is generating url rewrites (which executes as a blocking call) if they're needed. The idea is to analyze each step and see if we can save execution time by performing some of these actions at different times - like executing all url rewrite logic after the products have otherwise been saved. Can we save time by moving these around instead of executing product Save calls back-to-back-to-back in their current form? 

High level tasks: 
- Investigate url rewrite generation and provide a recommendation on how to handle them in a bulk product save API call
- Investigate what other steps in the product save operation can be moved around to save on execution time (do we have any other examples?)

**Comment by nuzil** [comment]
https://github.com/magento/async-import/issues/3
