### ISSUE TITLE
Add Swagger for Multiple Items

### ISSUE THREAD

**Issue by careys7** [magento-engcom/bulk-api#28]
Add Swagger support for https://github.com/magento-engcom/bulk-api/issues/20

Questions:

- ~~Is this a new schema type? eg `async_bulk`~~
- Is backward compatibility required for `ServiceMetadata::__construct()`?

**Comment by anvasiliev** [comment]
Hi Carey,
Asynchronous Bulk request route path prefix is /async/bulk/ (please check const in https://github.com/magento/bulk-api-ce/blob/2.3-develop/app/code/Magento/WebapiAsync/Controller/Rest/AsynchronousRequestProcessor.php#L29 )

Asynchronous Bulk Schema route path async/bulk/schema (please check const  https://github.com/magento/bulk-api-ce/blob/2.3-develop/app/code/Magento/WebapiAsync/Controller/Rest/AsynchronousSchemaRequestProcessor.php#L22 )

Notes: I saw that you check if current processor is async or not in plugin (https://github.com/magento/bulk-api-ce/blob/2.3-develop/app/code/Magento/WebapiAsync/Plugin/ServiceMetadata.php#L78 ), but in current implementation canProcess method will return true for single async and bulk async requests. For check that current request is async single or bulk you may need to add additional check by using method Magento\WebapiAsync\Controller\Rest\AsynchronousSchemaRequestProcessor::isBulk($request)
  https://github.com/magento/bulk-api-ce/blob/2.3-develop/app/code/Magento/WebapiAsync/Controller/Rest/AsynchronousSchemaRequestProcessor.php#L87

**Comment by careys7** [comment]
thanks @anvasiliev 

@vrann / others - I need to allow `ServiceMetadata` to accept a `ConfigInterface` so that I can create a bulk service metadata instance (which uses `BulkServiceConfig `):

https://github.com/magento/bulk-api-ce/blob/2.3-develop/app/code/Magento/Webapi/Model/ServiceMetadata.php#L92

What's the recommended approach to change this without breaking backward compatibility on `ServiceMetadata`?

**Comment by vrann** [comment]
@careys7 please check this article on adding constructor dependencies in backward compatible way http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/#adding-a-constructor-parameter

**Comment by careys7** [comment]
thanks @vrann - actually I need to replace:

`\Magento\Webapi\Model\Config $config`

with 

`\Magento\Webapi\Model\ConfigInterface $config`

Is this permitted? `Config` now implements `ConfigInterface`

**Comment by vrann** [comment]
@careys7 technically it is still backward incompatible, because somebody might hardly depend on Config in this context. However taking into account that ServiceMetadata is not a public interface, this change will be acceptable in the minor (2.3) Magento release.

**Comment by nuzil** [comment]
Moved 
https://github.com/magento/async-import/issues/25
