### ISSUE TITLE
Switch default queue to DB for async web API

### ISSUE THREAD

**Issue by vrann** [magento-engcom/bulk-api#29]
Right now default message queue for async web API is AMQP, which requires RabbitMQ to be available for all Magento 2.3 instances.

To prevent hard dependency on RabbitMQ, default queue should be changed to DB.

Implementation hints:

\Magento\WebapiAsync\Code\Generator\Config\RemoteServiceReader\Publisher::read
Magento/WebapiAsync/etc/queue_consumer.xml
Magento/WebapiAsync/etc/queue_topology.xml

Consider adding MassConsumer and MassPublisher to MysqlQueue

**Comment by nuzil** [comment]
https://github.com/magento/async-import/issues/19
