### ISSUE TITLE
Performance optimizations on Save for Single product endpoint

### ISSUE THREAD

**Issue by misha-kotov** [magento-engcom/bulk-api#5]
As a Magento developer, I would like the Catalog API endpoint on Save to be optimized so that  Save operations execute as quickly and efficiently as possible. 

The intention of this work is to investigate the current implementation of product Save operation and determine ways to optimize it further. Currently many different actions are performed by Magento as a result of a product save. One example of such action is generating url rewrites (which executes as a blocking call) if they're needed. 

```
\Magento\Catalog\Api\ProductRepository(ProductInterface[] $products): ProductInterface[]
```

High level tasks: 
- Investigate the current implementation of the Product Save operation and determine potential areas of optimization
- Implement the optimizations

**Comment by nuzil** [comment]
Not relevant to this project. 
Good task to create on public Magento repository
